### PR TITLE
Fix README.md link to Issues page

### PR DESCRIPTION
**Pull request by mandel01**

### CODE REVIEW

**Comment by mandel01** [comment]
One additional comment that perhaps should be rolled in here. The documentation lists the default for `--mincontiglen` as 1. I did not set this parameter but it seems that the default is 200. Should this also be corrected here? I can push another patch if i have this right.

```
[23:04:12] Skipping short (<200 bp) contig: <contig name>
```

**Comment by mandel01** [comment]
I'll close this. PR #169 is a duplicate of this. However, the line affected was changed in https://github.com/tseemann/prokka/commit/f61fd310439571d847583376bdffeb6073953b93. #169 was proposed after that change and therefore does not conflict with the current version of README.md.

**Comment by jaredo** [comment]
sorry!

**Comment by mandel01** [comment]
@jaredo no worries!

**Pull request closed without merging**
